### ISSUE TITLE
SetFont error

### ISSUE THREAD

**Issue by nancikennedy** [enderneko/IcyVeinsStatPriority#5]
On Retail...

1x Interface/AddOns/IcyVeinsStatPriority/Core.lua:79: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:79: in function <Interface/AddOns/IcyVeinsStatPriority/Core.lua:78>
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:733: in function `?'
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:718: in function <Interface/AddOns/IcyVeinsStatPriority/Core.lua:717>

Locals:
(*temporary) = IVSP_FONT {
 0 = <userdata>
}
(*temporary) = "Fonts\FRIZQT__.TTF"
(*temporary) = 11

**Comment by enderneko** [comment]
This should have been fixed yesterday.

**Comment by nancikennedy** [comment]
Yeah, it looks like it's all fine now.
