### ISSUE TITLE
10.0.2.46658 version, Phase 2 Patch

### ISSUE THREAD

**Issue by Wyveryx** [enderneko/IcyVeinsStatPriority#6]
After today's Pre Launch patch, 11/15, I'm getting the following error on the evoker.

5x Interface/AddOns/IcyVeinsStatPriority/Data.lua:178: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: in function `gsub'
[string "@Interface/AddOns/IcyVeinsStatPriority/Data.lua"]:178: in function <Interface/AddOns/IcyVeinsStatPriority/Data.lua:176>
[string "@Interface/AddOns/IcyVeinsStatPriority/Data.lua"]:211: in function `GetSPText'
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:759: in function `?'
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:718: in function <Interface/AddOns/IcyVeinsStatPriority/Core.lua:717>

Locals:
(*temporary) = nil
(*temporary) = "Haste"
(*temporary) = "Haste"
(*temporary) = "string expected, got nil"

**Comment by enderneko** [comment]
Fixed.
