### ISSUE TITLE
10.2.5 Color Picker Lua error

### ISSUE THREAD

**Issue by class2u** [enderneko/IcyVeinsStatPriority#7]
Hi, due to 10.2.5 Color Picker changes. Got the following Lua error when I try to change the text color.

2x IcyVeinsStatPriority/Core.lua:186: attempt to call method 'SetColorRGB' (a nil value)
[string "@IcyVeinsStatPriority/Core.lua"]:186: in function <IcyVeinsStatPriority/Core.lua:180>
[string "@IcyVeinsStatPriority/Core.lua"]:204: in function <IcyVeinsStatPriority/Core.lua:201>

Locals:
colorTable = <table> {
 1 = 0
 2 = 0
 3 = 0
 4 = 1
}
changedCallback = <function> defined @IcyVeinsStatPriority/Core.lua:151
r = 0
g = 0
b = 0
a = 1
(*temporary) = nil
(*temporary) = ColorPickerFrame {
 0 = <userdata>
 GetColorRGB = <function> defined @FrameXML/ColorPickerFrame.lua:79
 DragBar = Frame {
 }
 DriftHookSet = true
 OnKeyDown = <function> defined @FrameXML/ColorPickerFrame.lua:53
 cancelFunc = <function> defined @IcyVeinsStatPriority/Core.lua:151
 SetPoint = <function> defined =[C]:-1
 func = <function> defined @IcyVeinsStatPriority/Core.lua:151
 SetScale = <function> defined =[C]:-1
 SetupColorPickerAndShow = <function> defined @FrameXML/ColorPickerFrame.lua:62
 OnLoad = <function> defined @FrameXML/ColorPickerFrame.lua:3
 GetExtraInfo = <function> defined @FrameXML/ColorPickerFrame.lua:87
 previousValues = <table> {
 }
 GetPreviousValues = <function> defined @FrameXML/ColorPickerFrame.lua:91
 opacity = 1
 hasOpacity = true
 GetColorAlpha = <function> defined @FrameXML/ColorPickerFrame.lua:83
 Header = Frame {
 }
 Footer = Frame {
 }
 OnShow = <function> defined @FrameXML/ColorPickerFrame.lua:34
 Border = Frame {
 }
 Content = Frame {
 }
 opacityFunc = <function> defined @IcyVeinsStatPriority/Core.lua:151
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = "attempt to call method 'SetColorRGB' (a nil value)"

**Comment by enderneko** [comment]
Fixed.
Thanks for the feedback.
