### ISSUE TITLE
LUA issues in latest patch

### ISSUE THREAD

**Issue by dianegall** [enderneko/IcyVeinsStatPriority#9]
I understand that a bunch of functions were deprecated. So I am getting this:

Message: Interface/AddOns/IcyVeinsStatPriority/Core.lua:751: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Wed Aug 14 09:17:40 2024
Count: 1
Stack: Interface/AddOns/IcyVeinsStatPriority/Core.lua:751: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:751: in function `?'
[string "@Interface/AddOns/IcyVeinsStatPriority/Core.lua"]:726: in function <Interface/AddOns/IcyVeinsStatPriority/Core.lua:725>

Locals: self = IcyVeinsStatPriorityFrame {
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
arg1 = "IcyVeinsStatPriority"
(*temporary) = FontString {
}
(*temporary) = "Version: "
(*temporary) = nil
(*temporary) = "IcyVeinsStatPriority"
(*temporary) = "version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
addonName = "IcyVeinsStatPriority"
bgColorPicker = IcyVeinsBGColorPicker {
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
borderColorPicker = IcyVeinsBorderColorPicker {
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
fontColorPicker = IcyVeinsFontColorPicker {
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
versionText = FontString {
}

**Comment by enderneko** [comment]
Fixed
